# Server Configuration
server:
  port: 8034
  error:
    include-stacktrace: always
  compression:
    enabled: true
  address: 0.0.0.0

# Spring Configuration
spring:
  application:
    name: eteacher-service
  main:
    allow-bean-definition-overriding: true

  # Database Configuration
  datasource:
    url: jdbc:sqlserver://192.168.1.20:1433;databaseName=IEIMS_DEV_ONGOING_TEST
    username: ieims_dev
    password: "Ie!mSd(v21"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    # Hikari Configuration
    hikari:
      minimum-idle: 1
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

  # JPA Configuration
  jpa:
    # Properties
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        format_sql: true
        use_sql: true
        shutdown_on_session_factory_close: false
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
          legacy_limit_handler: true

    # Hibernate
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Servlet Configuration
  servlet:
    multipart:
      enabled: true
      location: /tmp
      max-file-size: 512MB
      max-request-size: 512MB
      resolve-lazily: false

  # Redis Configuration
#  redis:
#    host: 192.168.1.17
#    port: 6379

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.1.17:8002/auth/realms/banbeis/protocol/openid-connect/certs

  # Kafka Configuration
#  kafka:
#    producer:
#      bootstrap-servers: 192.168.1.17:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  #spring mail config
  mail:
    host: smtp.gmail.com
    port: 587
    username: eatlbanbeis@gmail.com
    password: eatl1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Service discovery configuration
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.1.17:8761/eureka/
#    healthcheck:
#      enabled: true
#  instance:
#    metadata-map:
#      instance-id: ${server.address}:${random.value}

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"

commonSettingService: ${commonSettingServiceBaseUrl:http://192.168.1.13:8000/}


employeeEncloserUploadPath: /home/sami/upload/employee-encloser
employeeEncloserDelationPath: //home//sami//upload//employee-encloser//
transferRecordEncloserUploadPath: /home/sami/upload/employee-transfer-record-encloser
transferRecordEncloserDelationPath: //home//sami//upload//employee-transfer-record-encloser//
pensionRequestEncloserUploadPath: /home/sami/upload/employee-pension-request-encloser
pensionRequestEncloserDelationPath: //home//sami//upload//employee-pension-request-record-encloser//
employeeJoiningEncloserUploadPath: /home/sami/upload/employee-joining-encloser
employeeJoiningEncloserDelationPath: //home//sami//upload//employee-joining-encloser//
attritionRecordUploadPath: /home/sami/upload/employee-attrition-record-encloser
attritionRecordDelationPath: //home//sami//upload//employee-attrition-record-encloser//
employeeLeaveRecordEncloserUploadPath: /home/sami/upload/employee-leave-record-encloser
employeeLeaveRecordDelationPath: //home//sami//upload//employee-leave-record-encloser//
jobPostingUploadPath: /home/sami/upload/employee-job-posting-encloser
jobPostingDelationPath: //home//sami//upload//employee-job-posting-encloser//
affiliationUploadPath: /home/sami/upload/employee-affiliation-encloser
affiliationDelationPath: //home//sami//upload//employee-affiliation-encloser//
mpoApplicationUploadPath: /home/sami/upload/employee-mpo-application-encloser
mpoApplicationDelationPath: //home//sami//upload//employee-mpo-application-encloser//
employeeMpoRetirementEncloserUploadPath: /home/sami/upload/employee-mpo-retirement-payment-encloser
employeeMpoRetirementEncloserDelationPath: //home//sami//upload//employee-mpo-retirement-payment-encloser//
employeeMpoReleaseRecordEncloserUploadPath: /home/sami/upload/employee-mpo-release-record-encloser
employeeMpoReleaseRecordEncloserDelationPath: //home//sami//upload//employee-mpo-release-record-encloser//
employeeMpoRetirementRequestEncloserUploadPath: /home/sami/upload/employee-mpo-retirement-request-encloser
employeeMpoRetirementRequestEncloserDelationPath: //home//sami//upload//employee-mpo-retirement-request-encloser//
